name: Core 2 - 2 jobs

on:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  core1:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
       TEST: 'testEscho'

    steps:
    - name: echo date core 1 before 
      run: date
    - name: core 1
      run: sudo apt-get install stress-ng&&sudo stress-ng --cpu 1 --yaml core1.yml --cpu-method matrixprod --metrics-brief -t 60
    - name: echo date core 1 after
      run: date
    
  core2:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
       TEST: 'testEscho'

    steps:
    - name: echo date core 2 before 
      run: date
    - name: core 2
      run: sudo apt-get install stress-ng&&sudo stress-ng --cpu 1 --yaml core2.yml --cpu-method matrixprod --metrics-brief -t 60
    - name: echo date core 2 after 
      run: date
